services:

  agent-ssh:
    image: jenkins/ssh-agent-python:latest
    container_name: docker-agent-ssh
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=$RSA_PUB
    ports:
      - 2222:22
    restart: on-failure


  jenkins-agent:
    image: jenkins/inbound-agent
    container_name: docker-agent-tcp
    environment:
      - JENKINS_URL=http://host.docker.internal:8080
      - JENKINS_AGENT_NAME=docker-agent-tcp
      - JENKINS_SECRET=$JENKINS_SECRET
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins-agent-workdir:/home/jenkins/agent

    restart: on-failure
  

volumes:
  jenkins-agent-workdir: